### ISSUE TITLE
hi, i am happy with the 

### ISSUE THREAD

**Issue by jar10623** [JChristensen/mini1284#1]
v1.0 now i found at osh park v1.1
what ist different ?
is there a link to the changes?

**Comment by JChristensen** [comment]
Only the crystal.
From https://github.com/JChristensen/mini1284/blob/v1.1/ReadMe.md:
"v1.1 differs from v1.0 only in that a different crystal and different value loading capacitors are used."
Check out the png images of the board in each branch and also the links to the bills of materials on Mouser. v1.0 uses [this Abracon crystal](http://www.mouser.com/Search/ProductDetail.aspx?R=ABM2-16.000MHZ-D4Y-Tvirtualkey52750000virtualkey815-ABM2-16-D4Y-T), v1.1 uses [this Epson crystal](http://www.mouser.com/Search/ProductDetail.aspx?R=TSX-3225_16.0000MF10U-B0virtualkey64320000virtualkey732-322516MF10U-B0). I was hoping to save board space with the Epson crystal but in the end I don't think it saved much, and the Epson crystal is more of a challenge to solder by hand.

Also on OSH Park, check [v1.0](https://644db4de3505c40a0444-327723bce298e3ff5813fb42baeefbaa.ssl.cf1.rackcdn.com/uploads/project/top_image/KaCh1X2a/i.png) vs. [v1.1](https://644db4de3505c40a0444-327723bce298e3ff5813fb42baeefbaa.ssl.cf1.rackcdn.com/uploads/project/top_image/AidBx1xb/i.png).

**Comment by jar10623** [comment]
oh thanks

i think for me the 1.0 is better on the 1.1 i see a 4 pad crystal? ok most of the buyable parts here ar 4 pad crystal, but the 2 pad is solder easyer only the Pads are to small, the buyable Parts here are so short they reached the pads very far. see: https://www.mikrocontroller.net/attachment/255241/mighty_flach1_2.jpg, i wounder only why you routed the FTDI lines on the head, 
see on the pic link
face to face to connected were more likely to me, but well done. if you made a 3th one i want a face to face ftdi connect and a smaller pcb for a dil48 socket
http://www.segor.de/bilder/00001eae.jpg?SEGOR=%5B%27S0604%27%2C%27DILLAB48%27%2C%27%27%2C%27%27%2C%27%27%2C%27%27%2C%27%27%2C%27%27%2C%27Pr%E4zisionssockel%20DIL48%27%2C%27Goldclip%27%2C%271%27%2C%271%27%2C%271%27%2C%271%27%2C%271%27%2C%271200%27%2C%271010%27%2C%2710%27%2C%27990%27%2C%27830%27%2C%2725%27%2C%27860%27%2C%27720%27%2C%27%27%2C%27%27%2C%27%27%2C%27%27%2C%27%27%2C%27%27%2C%27%27%2C%27%27%2C%27%27%2C%271eae%27%2C%276%27%2C%27%27%2C%270%27%2C%277854%27%5D
or a pcb i can put in a 64 motorola 68k socket
http://www.elmotex.de/images/dil-64p.jpg

**Comment by JChristensen** [comment]
Good looking boards, thanks for sharing. If I have more boards made, I'd probably just go with v1.0 as well.
