### ISSUE TITLE
need help with optiboot @22.1184 MHz & 921600 Baud 

### ISSUE THREAD

**Issue by jar10623** [JChristensen/mini1284#2]
befor for all of my 5 mighty 1284p ich use Optiboot for 1M @16MHz

now i change the crytal up to 22.1184 MHz, it works but i must build a new bootloader and i don't know how.

make (winavr) with target atmega1284p give a error

C:\optiboot>make atmega1284
/usr/local/avr/bin/avr-gcc -g -Wall -Os -fno-inline-small-functions -fno-split-w
ide-types -mshort-calls -mmcu=atmega1284p -DF_CPU=22118400L  '-DLED_START_FLASHE
S=3' '-DBAUD_RATE=115200' '-DBIGBOOT'   -c -o optiboot.o optiboot.c
process_begin: CreateProcess(NULL, /usr/local/avr/bin/avr-gcc -g -Wall -Os -fno-
inline-small-functions -fno-split-wide-types -mshort-calls -mmcu=atmega1284p -DF
_CPU=22118400L -DLED_START_FLASHES=3 -DBAUD_RATE=115200 -DBIGBOOT -c -o optiboot
.o optiboot.c, ...) failed.
make (e=3): Das System kann den angegebenen Pfad nicht finden.
make: **\* [optiboot.o] Error 3

path error, but wich path why ?
@win there is no /usr/local?

in avr studio 4.18 sr3 is a warning
../optiboot.c:256: warning: 'flash_led' declared 'static' but never defined

but i think that doesn't interessed

build was ok for hex but it doesn't work
i don't know where i must change the baudrate for 921600 Baud  and how put it in the boards.txt in arduino

**Comment by JChristensen** [comment]
See https://github.com/Optiboot/optiboot/wiki/CompilingOptiboot

**Comment by jar10623** [comment]
sorry that wouldn't help

this show the way to a java use in Arduino, but first
path not found -> the reason name in Arduino looks like avr-gcc 
but my win set path is to winavr gcc so avr-gcc is not found.

ok i have the optiboot sourcen an a aps für studio but there is the 
arduino led on PortB1 (1 Problem i found) i corrected to PB7

i think it dosn't work because no LED

then i think it dosn't work because 22 MHz and low voltage 4,3 to 4,7V

but this is not the reason

Bootloder is build good, programming is good with verify
the mighty started with my 5 flashes on LED and 22MHz

but i can not program via Arduino

i try 230400 Bd an put it in the mightys board.txt
same with 115200 Bd

i don't know what can i do, wich #defines wich options are missing?
on Arduino i see this Mistake, every try:

Binäre Sketchgröße: 1.606 Bytes (von einem Maximum von 130.048 Bytes)
avrdude: verification error, first mismatch at byte 0x0002
         0x67 != 0x46
avrdude: verification error; content mismatch

why work mighty with 1 M Bd? do you use avrdude?
why ist there a remark in the source

#if F_CPU > 16000000L
#define BAUD_RATE   230400L // Highest rate Avrdude win32 will support

how it is posible to use 1M and why is my mistake in AVRdude with 115k

**Comment by jar10623** [comment]
please would you help me build two

bootloader 
1. 22.1184 MHz @921600 Baud
2. 14.7456 MHz @115200 Baud
and better show me the way (peter frampton)
https://www.youtube.com/watch?v=zLgeTtYwQ7o

i think one MUST be work @arduino

**Comment by JChristensen** [comment]
Sorry, I just don't have the time at present. This is a bit off-topic for this repo anyway. Suggest trying the Arduino forum.

**Comment by jar10623** [comment]
arduino forum is big, have a link at the right place please?

all the same, with the fastLED Problem i get no help from autors because they have no 1284p an i must go my own way with F_CPU \* 10L/9L for m1284p

**Comment by JChristensen** [comment]
Microcontrollers
Standalone or alternative microcontrollers, in-system programming, bootloaders, etc.
http://forum.arduino.cc/index.php?board=67.0

**Comment by jar10623** [comment]
thanks

**Comment by jar10623** [comment]
sorry that the same problem before over arduino, i can not build.....

but i wounder why you build a 16MHz mighty?
1284p can go up to 20Mhz or maybe 22MHz
for Baudrate it is better to take an baud rate crystal 7.xx 14.xx

16 Mhz is so unusefull

**Comment by JChristensen** [comment]
The 1284P provides more flash and SRAM than the 328P, but its CPU specs are the same; it's not meant to address processing capacity. You're welcome to your opinion but I prefer conservative designs, and certainly not overclocking. Anyway, 20MHz represents only a marginal speed improvement over 16MHz. If I need something with more horsepower, I'd look to double or triple the clock speed and/or go to a 32-bit machine. 16MHz works well with the Arduino ecosystem and I've never had problems with baud rate tolerances.
